#  Pandas Optional Practice 40 Questions

Welcome to the **Pandas Practice Notebook**.  
This file includes a progressive set of 40 questions to help you master data manipulation and analysis using Pandas.

- **Q1–Q30:** Based on class notes (DataFrame creation, indexing, selection, filtering, grouping, merging, concat, etc.)  

- **Q31–Q35:** Intermediate to hard-level questions (multi-indexing, advanced groupby, pivot, date operations)  

- **Q36–Q40:** Based on the provided dataset `travel_bookings.csv`

Each question is self-explanatory and followed by a code cell marked `# answer here`.

### Q1. Import pandas and check its version.

In [ ]:
import pandas as pd
pd.__version__

'2.2.2'

### Q2. Create a Series from a list `[10, 20, 30, 40, 50]` with custom index labels A–E.

In [ ]:
list=[10,20,30,40,50]
index=["A","B","C","D","E",]

series=pd.Series(list,index)

print(series)

A    10
B    20
C    30
D    40
E    50
dtype: int64

### Q3. Create a DataFrame using a dictionary with columns: Name, Age, and City.

In [ ]:
data={
    "Name":["shivam","shubham","ankita"],
     "Age":[11,22,33],
     "City":["kld","gkp","lko"],
}

pd.DataFrame(data)

      Name  Age City
0   shivam   11  kld
1  shubham   22  gkp
2   ankita   33  lko

### Q4. Read a CSV file using `pd.read_csv()` and display first 5 rows.

In [ ]:
df=pd.read_csv("/content/sample_data/Student_CSV (1).csv").head()

In [ ]:
df1=pd.read_csv("/content/sample_data/Student_CSV (1).csv")

In [ ]:
df

  StudentID       Name       City  Age  Score  JoinedDate  IsActive
0      S001  Student_1       Pune   26  58.55  2024-01-01      True
1      S002  Student_2    Kolkata   22  76.41  2024-01-02     False
2      S003  Student_3    Kolkata   18  92.66  2024-01-03     False
3      S004  Student_4  Bengaluru   22  58.34  2024-01-04     False
4      S005  Student_5      Delhi   29  81.87  2024-01-05      True

### Q5. Display the shape, columns, and data types of a DataFrame.

In [ ]:
df.shape

(5, 7)

In [ ]:
df.columns

Index(['StudentID', 'Name', 'City', 'Age', 'Score', 'JoinedDate', 'IsActive'], dtype='object')

In [ ]:
print(df.dtypes)

StudentID      object
Name           object
City           object
Age             int64
Score         float64
JoinedDate     object
IsActive         bool
dtype: object

### Q6. Select a single column from a DataFrame and display its first 5 rows.

In [ ]:
new['City'].head()

0         Pune
1      Kolkata
2      Kolkata
3    Bengaluru
4        Delhi
Name: City, dtype: object

### Q7. Select multiple columns: 'Name' and 'City'.

In [ ]:
new[["Name","City"]][0:10]

         Name       City
0   Student_1       Pune
1   Student_2    Kolkata
2   Student_3    Kolkata
3   Student_4  Bengaluru
4   Student_5      Delhi
5   Student_6    Chennai
6   Student_7    Kolkata
7   Student_8       Pune
8   Student_9  Bengaluru
9  Student_10    Kolkata

### Q8. Access rows using `loc[]` and `iloc[]`. Display the first and last row using both.

In [ ]:
df.loc[0,"City"]

'Pune'

In [ ]:
df.loc[len(df)-1]

StudentID           S005
Name           Student_5
City               Delhi
Age                   29
Score              81.87
JoinedDate    2024-01-05
IsActive            True
Name: 4, dtype: object

In [ ]:
df.iloc[0]

StudentID           S001
Name           Student_1
City                Pune
Age                   26
Score              58.55
JoinedDate    2024-01-01
IsActive            True
Name: 0, dtype: object

In [ ]:
df.iloc[len(df)-1]

StudentID           S005
Name           Student_5
City               Delhi
Age                   29
Score              81.87
JoinedDate    2024-01-05
IsActive            True
Name: 4, dtype: object

### Q9. Filter rows where 'Age' > 30.

In [ ]:
new[new['Age']>30][0:50]

Empty DataFrame
Columns: [StudentID, Name, City, Age, Score, JoinedDate, IsActive]
Index: []

### Q10. Filter rows where 'City' is 'Delhi' or 'Mumbai'.

In [ ]:
new

   StudentID         Name       City  Age  Score  JoinedDate  IsActive
0       S001    Student_1       Pune   26  58.55  2024-01-01      True
1       S002    Student_2    Kolkata   22  76.41  2024-01-02     False
2       S003    Student_3    Kolkata   18  92.66  2024-01-03     False
3       S004    Student_4  Bengaluru   22  58.34  2024-01-04     False
4       S005    Student_5      Delhi   29  81.87  2024-01-05      True
..       ...          ...        ...  ...    ...         ...       ...
95      S096   Student_96  Bengaluru   22  95.57  2024-04-05     False
96      S097   Student_97  Bengaluru   26  72.55  2024-04-06     False
97      S098   Student_98      Delhi   22  49.99  2024-04-07      True
98      S099   Student_99     Mumbai   29  67.41  2024-04-08      True
99      S100  Student_100  Hyderabad   23  79.15  2024-04-09     False

[100 rows x 7 columns]

In [ ]:
new[new["City"].isin(["Delhi","Mumbai"])]

   StudentID        Name    City  Age  Score  JoinedDate  IsActive
4       S005   Student_5   Delhi   29  81.87  2024-01-05      True
27      S028  Student_28  Mumbai   19  78.59  2024-01-28     False
30      S031  Student_31  Mumbai   23  84.79  2024-01-31      True
33      S034  Student_34  Mumbai   28  43.48  2024-02-03      True
34      S035  Student_35   Delhi   19  98.67  2024-02-04     False
35      S036  Student_36  Mumbai   25  61.18  2024-02-05      True
37      S038  Student_38  Mumbai   27  54.77  2024-02-07      True
38      S039  Student_39   Delhi   25  51.88  2024-02-08     False
44      S045  Student_45   Delhi   24  82.99  2024-02-14     False
50      S051  Student_51  Mumbai   24  76.78  2024-02-20      True
51      S052  Student_52   Delhi   24  51.53  2024-02-21     False
58      S059  Student_59  Mumbai   29  84.29  2024-02-28     False
61      S062  Student_62   Delhi   19  44.38  2024-03-02      True
62      S063  Student_63  Mumbai   20  62.09  2024-03-03      True
70      S071  Student_71  Mumbai   25  70.38  2024-03-11     False
74      S075  Student_75   Delhi   18  41.90  2024-03-15      True
80      S081  Student_81  Mumbai   21  40.24  2024-03-21     False
83      S084  Student_84   Delhi   22  95.21  2024-03-24      True
87      S088  Student_88  Mumbai   24  71.16  2024-03-28      True
97      S098  Student_98   Delhi   22  49.99  2024-04-07      True
98      S099  Student_99  Mumbai   29  67.41  2024-04-08      True

In [ ]:
new[new["City"]=="Delhi"]

   StudentID        Name   City  Age  Score  JoinedDate  IsActive
4       S005   Student_5  Delhi   29  81.87  2024-01-05      True
34      S035  Student_35  Delhi   19  98.67  2024-02-04     False
38      S039  Student_39  Delhi   25  51.88  2024-02-08     False
44      S045  Student_45  Delhi   24  82.99  2024-02-14     False
51      S052  Student_52  Delhi   24  51.53  2024-02-21     False
61      S062  Student_62  Delhi   19  44.38  2024-03-02      True
74      S075  Student_75  Delhi   18  41.90  2024-03-15      True
83      S084  Student_84  Delhi   22  95.21  2024-03-24      True
97      S098  Student_98  Delhi   22  49.99  2024-04-07      True

### Q11. Sort a DataFrame by the 'Age' column in descending order.

In [ ]:
df1.sort_values(by="Age")

   StudentID        Name       City  Age  Score  JoinedDate  IsActive
2       S003   Student_3    Kolkata   18  92.66  2024-01-03     False
39      S040  Student_40    Chennai   18  83.34  2024-02-09      True
40      S041  Student_41  Bengaluru   18  82.39  2024-02-10      True
74      S075  Student_75      Delhi   18  41.90  2024-03-15      True
52      S053  Student_53       Pune   19  73.31  2024-02-22      True
..       ...         ...        ...  ...    ...         ...       ...
21      S022  Student_22  Bengaluru   30  79.10  2024-01-22      True
16      S017  Student_17  Bengaluru   30  78.77  2024-01-17      True
94      S095  Student_95    Chennai   30  88.45  2024-04-04      True
79      S080  Student_80       Pune   30  45.54  2024-03-20      True
86      S087  Student_87    Kolkata   30  83.96  2024-03-27     False

[100 rows x 7 columns]

### Q12. Add a new column 'Bonus' which is 10% of 'Salary'.

In [ ]:
df2=pd.read_csv("/content/sample_data/employees_data (3).csv")

In [ ]:
df2

     employee_id employee_name   age  department    salary
0              1       Rahul_1  22.0   Marketing  106025.0
1              2       Pooja_2  42.0  Operations   90456.0
2              3       Karan_3  52.0          IT  140734.0
3              4        Amit_4  44.0     Finance   66172.0
4              5       Vikas_5  52.0          HR   52535.0
..           ...           ...   ...         ...       ...
995          996     Rohit_996  31.0   Marketing   49808.0
996          997     Karan_997  29.0  Operations  192085.0
997          998      Amit_998  47.0          HR   21360.0
998          999     Rohit_999  34.0          HR  193382.0
999         1000    Rahul_1000  29.0     Finance   48603.0

[1000 rows x 5 columns]

In [ ]:
df2["Bonus"]=df2['salary']*10/100

In [ ]:
df2

     employee_id employee_name   age  department    salary    Bonus
0              1       Rahul_1  22.0   Marketing  106025.0  10602.5
1              2       Pooja_2  42.0  Operations   90456.0   9045.6
2              3       Karan_3  52.0          IT  140734.0  14073.4
3              4        Amit_4  44.0     Finance   66172.0   6617.2
4              5       Vikas_5  52.0          HR   52535.0   5253.5
..           ...           ...   ...         ...       ...      ...
995          996     Rohit_996  31.0   Marketing   49808.0   4980.8
996          997     Karan_997  29.0  Operations  192085.0  19208.5
997          998      Amit_998  47.0          HR   21360.0   2136.0
998          999     Rohit_999  34.0          HR  193382.0  19338.2
999         1000    Rahul_1000  29.0     Finance   48603.0   4860.3

[1000 rows x 6 columns]

### Q13. Replace missing values in 'Salary' with the mean salary.

In [ ]:
df2["salary"].isnull().sum()

np.int64(11)

In [ ]:
new_salary=df2["salary"].mean()

In [ ]:
df2["salary"].fillna(new_salary,inplace=True)#inplace=True is necessary in change original file

In [ ]:
df2

     employee_id employee_name   age  department    salary    Bonus
0              1       Rahul_1  22.0   Marketing  106025.0  10602.5
1              2       Pooja_2  42.0  Operations   90456.0   9045.6
2              3       Karan_3  52.0          IT  140734.0  14073.4
3              4        Amit_4  44.0     Finance   66172.0   6617.2
4              5       Vikas_5  52.0          HR   52535.0   5253.5
..           ...           ...   ...         ...       ...      ...
995          996     Rohit_996  31.0   Marketing   49808.0   4980.8
996          997     Karan_997  29.0  Operations  192085.0  19208.5
997          998      Amit_998  47.0          HR   21360.0   2136.0
998          999     Rohit_999  34.0          HR  193382.0  19338.2
999         1000    Rahul_1000  29.0     Finance   48603.0   4860.3

[1000 rows x 6 columns]

In [ ]:
df2["salary"].isnull().sum()

np.int64(0)

### Q14. Drop rows where any value is missing using `dropna()`.

In [ ]:
df2.isnull().sum()#THINK ABOUT IT,TRY AGAIN

employee_id       0
employee_name     0
age               5
department        0
salary            0
Bonus            11
dtype: int64

### Q15. Rename the column 'Name' to 'Employee_Name'.

In [ ]:
df2.rename({"Name":"Employee_Name"})

     employee_id employee_name   age  department    salary    Bonus
0              1       Rahul_1  22.0   Marketing  106025.0  10602.5
1              2       Pooja_2  42.0  Operations   90456.0   9045.6
2              3       Karan_3  52.0          IT  140734.0  14073.4
3              4        Amit_4  44.0     Finance   66172.0   6617.2
4              5       Vikas_5  52.0          HR   52535.0   5253.5
..           ...           ...   ...         ...       ...      ...
995          996     Rohit_996  31.0   Marketing   49808.0   4980.8
996          997     Karan_997  29.0  Operations  192085.0  19208.5
997          998      Amit_998  47.0          HR   21360.0   2136.0
998          999     Rohit_999  34.0          HR  193382.0  19338.2
999         1000    Rahul_1000  29.0     Finance   48603.0   4860.3

[1000 rows x 6 columns]

### Q16. Use `groupby()` on 'City' and find the average of 'Salary'.

In [ ]:
new.groupby("City")["Score"].mean()

City
Bengaluru    76.023125
Chennai      74.010000
Delhi        66.491111
Hyderabad    73.418889
Kolkata      71.533750
Mumbai       66.263333
Pune         61.432000
Name: Score, dtype: float64

### Q17. Count how many employees are from each 'Department'.

In [ ]:
df2.groupby("department").size()

department
Finance       156
HR            171
IT            164
Marketing     162
Operations    166
Sales         181
dtype: int64

### Q18. Create a pivot table with 'Department' as index and average 'Salary' as values.

In [ ]:
df2.pivot_table(index="department",values="salary",aggfunc="mean")

                   salary
department
Finance     107506.525084
HR          108544.510552
IT          116615.794008
Marketing   105711.748792
Operations  112092.068098
Sales       109583.416046

### Q19. Concatenate two DataFrames vertically using `pd.concat()`.

In [ ]:
df2

     employee_id employee_name   age  department    salary    Bonus
0              1       Rahul_1  22.0   Marketing  106025.0  10602.5
1              2       Pooja_2  42.0  Operations   90456.0   9045.6
2              3       Karan_3  52.0          IT  140734.0  14073.4
3              4        Amit_4  44.0     Finance   66172.0   6617.2
4              5       Vikas_5  52.0          HR   52535.0   5253.5
..           ...           ...   ...         ...       ...      ...
995          996     Rohit_996  31.0   Marketing   49808.0   4980.8
996          997     Karan_997  29.0  Operations  192085.0  19208.5
997          998      Amit_998  47.0          HR   21360.0   2136.0
998          999     Rohit_999  34.0          HR  193382.0  19338.2
999         1000    Rahul_1000  29.0     Finance   48603.0   4860.3

[1000 rows x 6 columns]

In [ ]:
df1

   StudentID         Name       City  Age  Score  JoinedDate  IsActive
0       S001    Student_1       Pune   26  58.55  2024-01-01      True
1       S002    Student_2    Kolkata   22  76.41  2024-01-02     False
2       S003    Student_3    Kolkata   18  92.66  2024-01-03     False
3       S004    Student_4  Bengaluru   22  58.34  2024-01-04     False
4       S005    Student_5      Delhi   29  81.87  2024-01-05      True
..       ...          ...        ...  ...    ...         ...       ...
95      S096   Student_96  Bengaluru   22  95.57  2024-04-05     False
96      S097   Student_97  Bengaluru   26  72.55  2024-04-06     False
97      S098   Student_98      Delhi   22  49.99  2024-04-07      True
98      S099   Student_99     Mumbai   29  67.41  2024-04-08      True
99      S100  Student_100  Hyderabad   23  79.15  2024-04-09     False

[100 rows x 7 columns]

In [ ]:
combine=pd.concat([df1,df2])

In [ ]:
combine

,StudentID,Name,City,Age,Score,JoinedDate,IsActive,employee_id,employee_name,age,department,salary,Bonus
0,S001,Student_1,Pune,26.0,58.55,2024-01-01,True,NaN,NaN,NaN,NaN,NaN,NaN
1,S002,Student_2,Kolkata,22.0,76.41,2024-01-02,False,NaN,NaN,NaN,NaN,NaN,NaN
2,S003,Student_3,Kolkata,18.0,92.66,2024-01-03,False,NaN,NaN,NaN,NaN,NaN,NaN
3,S004,Student_4,Bengaluru,22.0,58.34,2024-01-04,False,NaN,NaN,NaN,NaN,NaN,NaN
4,S005,Student_5,Delhi,29.0,81.87,2024-01-05,True,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,996.0,Rohit_996,31.0,Marketing,49808.0,4980.8
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,997.0,Karan_997,29.0,Operations,192085.0,19208.5
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,998.0,Amit_998,47.0,HR,21360.0,2136.0
998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,999.0,Rohit_999,34.0,HR,193382.0,19338.2
999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.0,Rahul_1000,29.0,Finance,48603.0,4860.3

### Q20. Merge two DataFrames on a common column 'Employee_ID'.

In [ ]:
employees = {
"emp_id": [101,102,103,104,105,106,107,108,109,110,111,112,113,114,115],
"name": ["Aman","Riya","Karan","Neha","Arjun","Simran","Rahul","Priya","Vikas","Sneha","Ankit","Pooja","Rohit","Meena","Sahil"],
"age": [25,28,None,32,29,27,35,None,31,26,30,29,None,33,28],
"department_id": [1,2,1,3,2,1,3,2,None,1,2,3,1,None,2],
"salary": [50000,60000,55000,None,70000,52000,80000,62000,58000,None,75000,82000,54000,61000,None],
"city": ["Delhi","Mumbai","Delhi","Bangalore","Mumbai","Delhi","Bangalore","Mumbai","Delhi","Delhi","Mumbai","Bangalore","Delhi","Mumbai","Delhi"]
}









departments = {
"department_id": [1,2,3,4],
"department_name": ["HR","Sales","IT","Marketing"],
"location": ["Delhi","Mumbai","Bangalore","Chennai"]
}



bonuses = {
"emp_id": [101,102,104,106,108,110,112],
"bonus": [5000,7000,6000,4000,4500,5000,6500]
}

emp=pd.DataFrame(employees)

dept=pd.DataFrame(departments)
bonus=pd.DataFrame(bonuses)

In [ ]:
merged_df   =   pd.merge(emp,bonus,on="emp_id",how="left")

In [ ]:
merged_df

    emp_id    name   age  department_id   salary       city   bonus
0      101    Aman  25.0            1.0  50000.0      Delhi  5000.0
1      102    Riya  28.0            2.0  60000.0     Mumbai  7000.0
2      103   Karan   NaN            1.0  55000.0      Delhi     NaN
3      104    Neha  32.0            3.0      NaN  Bangalore  6000.0
4      105   Arjun  29.0            2.0  70000.0     Mumbai     NaN
5      106  Simran  27.0            1.0  52000.0      Delhi  4000.0
6      107   Rahul  35.0            3.0  80000.0  Bangalore     NaN
7      108   Priya   NaN            2.0  62000.0     Mumbai  4500.0
8      109   Vikas  31.0            NaN  58000.0      Delhi     NaN
9      110   Sneha  26.0            1.0      NaN      Delhi  5000.0
10     111   Ankit  30.0            2.0  75000.0     Mumbai     NaN
11     112   Pooja  29.0            3.0  82000.0  Bangalore  6500.0
12     113   Rohit   NaN            1.0  54000.0      Delhi     NaN
13     114   Meena  33.0            NaN  61000.0     Mumbai     NaN
14     115   Sahil  28.0            2.0      NaN      Delhi     NaN

### Q21. Sort the DataFrame based on multiple columns: 'City' then 'Age'.

In [ ]:
df.sort_values(by="Age",)

  StudentID       Name       City  Age  Score  JoinedDate  IsActive
2      S003  Student_3    Kolkata   18  92.66  2024-01-03     False
1      S002  Student_2    Kolkata   22  76.41  2024-01-02     False
3      S004  Student_4  Bengaluru   22  58.34  2024-01-04     False
0      S001  Student_1       Pune   26  58.55  2024-01-01      True
4      S005  Student_5      Delhi   29  81.87  2024-01-05      True

In [ ]:
df.sort_values(by="City",)

  StudentID       Name       City  Age  Score  JoinedDate  IsActive
3      S004  Student_4  Bengaluru   22  58.34  2024-01-04     False
4      S005  Student_5      Delhi   29  81.87  2024-01-05      True
1      S002  Student_2    Kolkata   22  76.41  2024-01-02     False
2      S003  Student_3    Kolkata   18  92.66  2024-01-03     False
0      S001  Student_1       Pune   26  58.55  2024-01-01      True

### Q22. Display the top 5 rows with the highest 'Salary'.

In [ ]:
 df2.nlargest(6,"salary")

     employee_id employee_name   age department    salary    Bonus
478          479    Anjali_479  39.0         HR  199991.0  19999.1
213          214     Pooja_214  57.0    Finance  199645.0  19964.5
812          813    Anjali_813  23.0  Marketing  199467.0  19946.7
403          404      Neha_404  53.0         IT  198678.0  19867.8
296          297     Rahul_297  47.0      Sales  198543.0  19854.3
304          305     Karan_305  39.0      Sales  198341.0  19834.1

### Q23. Find the employee(s) with the maximum and minimum salary.

In [ ]:
 df2.sort_values(by="salary").head()#minimum salary

     employee_id employee_name   age  department   salary   Bonus
63            64      Rahul_64  50.0          HR  20040.0  2004.0
936          937      Amit_937  46.0          IT  20081.0  2008.1
195          196     Karan_196  49.0     Finance  20335.0  2033.5
775          776     Priya_776  31.0  Operations  20585.0  2058.5
319          320     Vikas_320  59.0       Sales  20745.0  2074.5

In [ ]:
 df2.sort_values(by="salary",ascending=False).head()#top 5 salary

     employee_id employee_name   age department    salary    Bonus
478          479    Anjali_479  39.0         HR  199991.0  19999.1
213          214     Pooja_214  57.0    Finance  199645.0  19964.5
812          813    Anjali_813  23.0  Marketing  199467.0  19946.7
403          404      Neha_404  53.0         IT  198678.0  19867.8
296          297     Rahul_297  47.0      Sales  198543.0  19854.3

### Q24. Use `value_counts()` to count the number of unique cities.

In [ ]:
df["City"].value_counts()

City
Kolkata      2
Pune         1
Bengaluru    1
Delhi        1
Name: count, dtype: int64

### Q25. Change data type of 'Salary' column to integer using `astype()`.

In [ ]:
df2["salary"]=df2["salary"].astype(int)

In [ ]:
print(df2.dtypes)

employee_id        int64
employee_name     object
age              float64
department        object
salary             int64
Bonus            float64
dtype: object

### Q26. Reset and set a new index on the DataFrame.

In [ ]:
import pandas as pd

In [ ]:
df3=pd.read_csv("/content/sample_data/Student_CSV (1).csv")

In [ ]:
df3.reset_index(drop=True)
df3.set_index("Name")

            StudentID       City  Age  Score  JoinedDate  IsActive
Name
Student_1        S001       Pune   26  58.55  2024-01-01      True
Student_2        S002    Kolkata   22  76.41  2024-01-02     False
Student_3        S003    Kolkata   18  92.66  2024-01-03     False
Student_4        S004  Bengaluru   22  58.34  2024-01-04     False
Student_5        S005      Delhi   29  81.87  2024-01-05      True
...               ...        ...  ...    ...         ...       ...
Student_96       S096  Bengaluru   22  95.57  2024-04-05     False
Student_97       S097  Bengaluru   26  72.55  2024-04-06     False
Student_98       S098      Delhi   22  49.99  2024-04-07      True
Student_99       S099     Mumbai   29  67.41  2024-04-08      True
Student_100      S100  Hyderabad   23  79.15  2024-04-09     False

[100 rows x 6 columns]

### Q27. Extract rows using conditional filtering with multiple conditions (e.g., Age > 25 and Salary > 40000).

In [ ]:
df3[(df3["Age"]>25) &  ( df3["Score"]>80)]

   StudentID        Name       City  Age  Score  JoinedDate  IsActive
4       S005   Student_5      Delhi   29  81.87  2024-01-05      True
15      S016  Student_16    Chennai   29  87.01  2024-01-16      True
31      S032  Student_32  Bengaluru   28  85.30  2024-02-01     False
53      S054  Student_54    Kolkata   27  91.29  2024-02-23      True
56      S057  Student_57    Chennai   27  85.66  2024-02-26     False
57      S058  Student_58  Hyderabad   27  82.65  2024-02-27      True
58      S059  Student_59     Mumbai   29  84.29  2024-02-28     False
66      S067  Student_67    Chennai   29  89.04  2024-03-07      True
71      S072  Student_72    Kolkata   26  84.85  2024-03-12      True
86      S087  Student_87    Kolkata   30  83.96  2024-03-27     False
88      S089  Student_89       Pune   28  83.38  2024-03-29     False
90      S091  Student_91  Bengaluru   28  97.14  2024-03-31      True
94      S095  Student_95    Chennai   30  88.45  2024-04-04      True

### Q28. Find unique values and their counts in 'Department' column.

In [12]:
import pandas as pd

In [14]:
df=pd.read_csv("/content/sample_data/employees_data.csv")

In [15]:
df.columns

Index(['employee_id', 'employee_name', 'age', 'department', 'salary'], dtype='object')

In [18]:
df["department"].value_counts()

department
Sales         181
HR            171
Operations    166
IT            164
Marketing     162
Finance       156
Name: count, dtype: int64

In [19]:
df["department"].nunique()

6

In [20]:
df["department"].unique()

array(['Marketing', 'Operations', 'IT', 'Finance', 'HR', 'Sales'],
      dtype=object)

### Q29. Create a new column 'Experience_Level' based on condition: if Age>35 → 'Senior', else 'Junior'.

In [21]:
df

     employee_id employee_name  age  department  salary
0              1       Rahul_1   22   Marketing  106025
1              2       Pooja_2   42  Operations   90456
2              3       Karan_3   52          IT  140734
3              4        Amit_4   44     Finance   66172
4              5       Vikas_5   52          HR   52535
..           ...           ...  ...         ...     ...
995          996     Rohit_996   31   Marketing   49808
996          997     Karan_997   29  Operations  192085
997          998      Amit_998   47          HR   21360
998          999     Rohit_999   34          HR  193382
999         1000    Rahul_1000   29     Finance   48603

[1000 rows x 5 columns]

In [37]:
df["Experience_Level"]="Junior"
df.loc[df['age'] > 35, 'Experience_Level'] = 'Senior'

In [41]:
df

,employee_id,employee_name,age,department,salary,Experience_Leve,Experience_Level
0,1,Rahul_1,22,Marketing,106025,junior,Junior
1,2,Pooja_2,42,Operations,90456,junior,Senior
2,3,Karan_3,52,IT,140734,junior,Senior
3,4,Amit_4,44,Finance,66172,junior,Senior
4,5,Vikas_5,52,HR,52535,junior,Senior
...,...,...,...,...,...,...,...
995,996,Rohit_996,31,Marketing,49808,junior,Junior
996,997,Karan_997,29,Operations,192085,junior,Junior
997,998,Amit_998,47,HR,21360,junior,Senior
998,999,Rohit_999,34,HR,193382,junior,Junior
999,1000,Rahul_1000,29,Finance,48603,junior,Junior

### Q30. Export the cleaned DataFrame to a new CSV file.

In [42]:
df.to_excel("firsr_file.xlsx")

In [44]:
df.to_csv("first_file.csv")

### Q31. Create a MultiIndex DataFrame with Department and City as hierarchical indexes and compute mean Salary per level.

In [61]:
new=df.groupby(["department","age"])["salary"].mean()

In [63]:
new

department  age
Finance     21     122721.500000
            22      83922.230769
            23     102624.000000
            24     128389.500000
            25      74202.000000
                       ...
Sales       56     146948.400000
            57     116528.600000
            58     118291.250000
            59     100113.833333
            60     102570.800000
Name: salary, Length: 234, dtype: float64

In [62]:
new.to_excel("hierarchy_data.xlsx")

### Q32. Use `apply()` to calculate the length of each employee name and store it in a new column 'Name_Length'.

In [65]:
df["name_length"]=df["employee_name"].apply(len)

In [66]:
df

,employee_id,employee_name,age,department,salary,Experience_Leve,Experience_Level,name_length
0,1,Rahul_1,22,Marketing,106025,junior,Junior,7
1,2,Pooja_2,42,Operations,90456,junior,Senior,7
2,3,Karan_3,52,IT,140734,junior,Senior,7
3,4,Amit_4,44,Finance,66172,junior,Senior,6
4,5,Vikas_5,52,HR,52535,junior,Senior,7
...,...,...,...,...,...,...,...,...
995,996,Rohit_996,31,Marketing,49808,junior,Junior,9
996,997,Karan_997,29,Operations,192085,junior,Junior,9
997,998,Amit_998,47,HR,21360,junior,Senior,8
998,999,Rohit_999,34,HR,193382,junior,Junior,9
999,1000,Rahul_1000,29,Finance,48603,junior,Junior,10

### Q33. Combine two DataFrames having different columns using `merge(how='outer')`.

### Q34. For a sales DataFrame with 'Date' column, extract 'Year' and 'Month' using `dt` accessor.

### Q35. Perform groupby on multiple columns ('City', 'Department') and find both mean and sum of Salary.

### Dataset for Q36–Q40

We will use **Travel Booking Dataset** available in `travel_bookings.csv`.  
Columns include: Booking_ID, Customer_Name, Destination, Travel_Type, Price, Seats, Travel_Date, Booking_Date, City, Rating.

### Q36. Load `travel_bookings.csv` into a DataFrame named `df`. Display its first 5 rows and info.

### Q37. Find the total number of bookings per 'Destination'. Display in descending order of booking count.

### Q38. Calculate the average 'Price' for each 'Travel_Type'.

### Q39. Find the highest rated destination and print its average rating.

### Q40. Find which city generated the highest total revenue (Price × Seats).